# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           starius37.github.io/:year/:month/:day/:title/
relative_permalinks: true


# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://starius37.github.io
baseurl:             ''

#pagination
gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# About/contact
author:
  name:              Sangbin Ham
  url:               https://twitter.com/mdo
  email:             starius37@likelion.net

# Custom vars
version:             1.0.0
